apiVersion: v1
kind: Service
metadata:
  name: dev-box-ssh
  namespace: default
spec:
  type: NodePort
  selector:
    app: dev-box
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
      nodePort: 30784
